version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      -postgre_data:/var/lib/postgressql/data/

  web :
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      -"8000:8000"

  volumes:
    postgre_data: